[package]
name = "BasicCoin"
version = "0.0.0"

[addresses]
NamedAddr = "0xCAFE"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-framework'